### PR TITLE
Typescript rewrite

### LINKED ISSUE #64: Split up GraphQL's schema.js file
It's getting real big! Time to split it up. We should have a discussion on how we want to split up that file.

### LINKED ISSUE #182: GraphQL Units not always Float
Running this query gives an error: We had this error before, but it wasn't discovered. While the query will still return data, the units for those this case affects, returns null fort he units field.
`Float cannot represent non numeric value: \"2-5\"`

```
{
  schedule(year:2019, quarter: "Fall", department:"COMPSCI") {
    units
    course {
      id
    }
}
```

The issue is some classes like `COMPSCI 199`, don't give units as a single number, but a range of numbers like 2-5. This can't be converted to a Float, so it is throwing the error. 

I see a few options in tackling this, 
 - Return a list of floats. so it would be like [2, 5]. This is what we do for Course Types.
 - Return it as a string. Let the user decide what to do with the data. A String is returned in our REST API
 - Use Union Types in GraphQL:
   - https://graphql.org/graphql-js/type/#graphqluniontype

### PR DESCRIPTION
**Pull request by ramanxg**
## Reference Issues
TypeScript Full rewrite
Closes #64  for splitting up GraphQL Schema.
Closes #182 bug.

## Summary of Change/Fix 
Rewrites our API into typescript, and many other changes. There are a lot of commits, primarily for testing deployment (since we need to do something separate for typescript). Once approved, I will write a summary like (below) in the squash and merge to master.

Some big changes include:
- Uses ES6 syntax for importing, which helps fix bugs with GraphQL split.
- Rewrite our tests, to support even more queries, and cover more of our code.
  - Some big changes: no graphql tests can have `errors` in its results. 
  - Added graphql queries that Zotistics uses. 
  - Removed tests that were used twice. API test helper now just proves supertest request agent, and has no tests. 
  - Separated rest tests into a new folder. 
- Uses `serverless-plugin-typescript` to deploy to serverless with typescript. 
- Changes to grades helper. 
  - Updates grades helper to use an optional parameter for connections
  - Changes the select * to return null for averageGPA
- Updated dependencies, and moved some over to dev dependencies.  
- Moving our deployment to node 14. 
  - Uses circleci's official serverless orb for setting up environment.

## Test Plan
Run `npm test` to test new changes. 

Test these endpoints: 

#### Courses
http://localhost:8080/rest/v0/courses/all
http://localhost:8080/rest/v0/courses/COMPSCI171
http://localhost:8080/rest/v0/courses/ECON1
#### Instructors
http://localhost:8080/rest/v0/instructors/all
http://localhost:8080/rest/v0/instructors/thornton
http://localhost:8080/rest/v0/instructors/kakagi
#### Grades
http://localhost:8080/rest/v0/grades/raw
http://localhost:8080/rest/v0/grades/calculated
http://localhost:8080/rest/v0/grades/raw?year=2018-19;2019-20&instructor=PATTIS,%20R.&department=I%26C%20SCI&quarter=Fall&division=LowerDiv
http://localhost:8080/rest/v0/grades/raw?department=I%26C%20SCI&division=upperdiv

http://localhost:8080/rest/v0/grades/calculated?year=2018-19;2019-20&instructor=PATTIS,%20R.&department=I%26C%20SCI&quarter=Fall&division=LowerDiv
http://localhost:8080/rest/v0/grades/calculated?department=I%26C%20SCI&division=upperdiv
#### SOC
http://localhost:8080/rest/v0/schedule/soc?term=2022%20Summer2&department=I%26C%20SCI&courseNumber=6B
http://localhost:8080/rest/v0/schedule/soc?term=2016%20Fall&sectionCodes=28127

http://localhost:8080/rest/v0/schedule/soc (This should return error)
#### Week
http://localhost:8080/rest/v0/schedule/week?year=2020&month=01&day=30
http://localhost:8080/rest/v0/schedule/week

#### Playground
http://localhost:8080/graphql-playground

#### Queries
```
{
  week(year:"2022", month: "02", day: "07") {
    week
    quarter
    display
  }
}
```
```
{
    grades(year:"2020-21", quarter:"FALL", instructor:"PATTIS, R.", department:"I&C SCI") {
      aggregate {
        average_gpa
      }
      grade_distributions {
        grade_a_count
        course_offering {
          year
          section {
            code
          }
          quarter
          course {
            department
          }
          instructors {
            shortened_name
            name
          }
        }
      }
    instructors 
    }
  }
```
```
{
    course(id:"COMPSCI161") {
    	id
    	department
    	offerings(year:2020, quarter:"Fall") {
        instructors {
          ucinetid
          shortened_name
        }
      }
  }
}
```
```
{
    schedule(year: 2022, quarter: "Summer2", department:"I&C SCI", course_number:"6B") {
      year
      quarter
      num_section_enrolled
      num_total_enrolled
      num_on_waitlist
      num_requested
      num_new_only_reserved
      course {
        id
        department
        description
      }
    }
  }
```

## Future Followup
- Include queries used by PeterPortal in GraphQL for our tests. (eventually AntAlmanac, when they switch over). 
- Add type checking for Current Week Endpoint
- Add testing for current week endpoint.

### CODE REVIEW

**Comment by ChaseC99** [comment]
Sorry still in the process of reviewing this... that's a lot of lines of code 😅 
In the future, I think we should create a feature branch and then do smaller PRs to that. It's much easier to review many small PRs than 1 large PR.

File: graphql/schema.ts [hunk 1]
```diff
@@ -0,0 +1,251 @@
...
+      type: weekType,
+      //date argument
+      args: {
+        year: { type: GraphQLString, description: "Must be in ISO 8601 extended format `YYYY`. "},
+        month: { type: GraphQLString, description: "Must be in ISO 8601 extended format `MM`. "},
+        day: { type: GraphQLString, description: "Must be in ISO 8601 extended format `DD`. "}
+      },
+
+      //calls getWeek(), fetching from UCI's academic calendar
+      resolve: async (_, {year, month, day}) => {
```
Comment (Edwu29) [inline graphql/schema.ts:131]: I think its helpful to declare the types for the resolve function arguments. Ex. year : str, month : str, day : str

**Review by Edwu29 — COMMENTED** [review]
Theres more type declarations in /graphql but test plan seems to be working fine

File: helpers/week.helper.ts [hunk 2]
```diff
@@ -244,4 +244,5 @@ function addDays(date, days) {
     date.setDate(date.getDate() + days);
```
Comment (Edwu29) [inline helpers/week.helper.ts:244]: can add type declaration for `yearInput`, `month` and `day` as well

File: graphql/schema.ts [hunk 3]
```diff
@@ -0,0 +1,251 @@
...
+    instructor: {
+      type: instructorType,
+
+      // specify args to query by (ucinetid)
+      args: {
+        ucinetid: { type: new GraphQLNonNull(GraphQLString), description: "ucinetid of a specific instructor. Ex: mikes"}
+      },
+
+      // define function to get a instructor
+      resolve: (_, {ucinetid}) => {
```
Comment (Edwu29) [inline graphql/schema.ts:51]: same here, type strring

File: graphql/schema.ts [hunk 4]
```diff
@@ -0,0 +1,251 @@
...
+    course: {
+      type: courseType,
+
+      // specify args to query by
+      args: {
+        id: { type: new GraphQLNonNull(GraphQLString), description: "Course Department concatenated with Course Number. Ex: COMPSCI161" }
+      },
+
+      // define function to get a course
+      resolve: (_, {id}) => {
```
Comment (Edwu29) [inline graphql/schema.ts:33]: and here

File: graphql/schedule.ts [hunk 5]
```diff
@@ -0,0 +1,127 @@
...
+    }
+  })
+});
+
+// Validate Schedule Query Arguments
+function validateScheduleArgs(args) {
+  // Assert that a term is provided (year and quarter)
+  // year and quarter are non-nullable, so they should never be false
+  if (!(args.year && args.quarter)) {
+    throw new ValidationError("Must provdide both a year and a quarter.");
```
Comment (Edwu29) [inline graphql/schedule.ts:119]: small typo here

File: graphql/schema.ts [hunk 6]
```diff
@@ -0,0 +1,251 @@
...
+        start_time: { type: GraphQLString, description: "Start time of a couse in 12 hour format. Ex: '10:00AM' or '5:00PM'" },
+        end_time: { type: GraphQLString, description: "End time of a couse in 12 hour format. Ex: '10:00AM' or '5:00PM'" },
+        max_capacity: { type: GraphQLString, description: "Maximum enrollment capacity of a choice. Specify a " },
+        full_courses: { type: GraphQLString, description: "Status of a course's enrollment state. ['ANY'|'SkipFullWaitlist'|'FullOnly'|'OverEnrolled']. Default: 'ANY'." },
+        cancelled_courses: { type: GraphQLString, description: "Indicate whether to ['Exclude'|'Include'|'Only'] cancelled courses. Default: 'EXCLUDE'." },
+        building: { type: GraphQLString, description: "Building code found on https://www.reg.uci.edu/addl/campus/." },
+        room: { type: GraphQLString, description: "Room number in a building. Must also specify a building code." }
+      },
+
+      resolve: async (_, args) => {
```
Comment (Edwu29) [inline graphql/schema.ts:110]: not sure what args type is here.. do we have a type for that? If not can leave it be

**Comment by ramanxg** [comment]
> Sorry still in the process of reviewing this... that's a lot of lines of code 😅 
> In the future, I think we should create a feature branch and then do smaller PRs to that. It's much easier to review many small PRs than 1 large PR.

Sorry about that. I actually had that before, but I ended up not reviewing those and instead wanting this one to be reviewed. Will definitely keep that in mind next time.

File: graphql/schema.ts [hunk 7]
```diff
@@ -0,0 +1,251 @@
...
+        // Get the fields requested in the query
+        // This allows us to only fetch what the client wants from sql
+        const requestedFields : string[] = Object.keys(parseResolveInfo(info).fieldsByTypeName.GradeDistributionCollection)
+      
+        // Construct a WHERE clause from the arguments
+        const where : WhereParams = parseGradesParamsToSQL(args);
+        
+        // If requested, retrieve the grade distributions
+        let grade_distributions;
+        let gradeResults : GradeRawData = undefined;
```
Comment (Edwu29) [inline graphql/schema.ts:166]: A little confused with the naming convention here with `GradeRawData` and `GradeDist` and maybe creating a type for `grade_distributions` since that's what we're returning? What I had in mind for the type names was similar to the GraphQL types. Ex. `grade_distributions ` be type `GradeDist`, `grade_results` can stay `GradeRawData` and `agreggate` be `GradeDistAggregate` or `GradeDistAgg`. Thats more intuitive to me, idk I could be wrong

**Review by Edwu29 — CHANGES_REQUESTED** [review]

File: graphql/schema.ts (hunk 1 above)
Comment (ramanxg) [reply graphql/schema.ts:131]: For destructuring objects in TypeScript, we can't give each variable a type like, `{year : string, month : string, day : string}`. It won't let me do that. I would have to give the entire object a type or interface, but I didn't think that was necessary. Because GraphQL gives it to us as a string, it will have to be a string, so we don't need to enforce the type on our own. 

I can add a type for the week helper method, so that it can be checked there.

File: graphql/schema.ts (hunk 3 above)
Comment (ramanxg) [reply graphql/schema.ts:51]: See https://github.com/icssc/peterportal-public-api/pull/172#discussion_r863189988

File: graphql/schema.ts (hunk 4 above)
Comment (ramanxg) [reply graphql/schema.ts:33]: See https://github.com/icssc/peterportal-public-api/pull/172#discussion_r863189988

File: graphql/schema.ts (hunk 6 above)
Comment (ramanxg) [reply graphql/schema.ts:110]: I think the args object is too variable to need a type, so I didn't add one. We validate it ourselves, and it's provided by GraphQL, so it shouldn't have errors.

File: graphql/schema.ts (hunk 7 above)
Comment (ramanxg) [reply graphql/schema.ts:166]: The object type of `grade_distributions` is only used here, so I didn't think to add a type. I'll add one but since it's formatted to be for GraphQL, I think we can use a different name, like `GradeGQLData`. Since it's the `GradeRawData` formatted for GraphQL. 

Thoughts?

File: helpers/week.helper.ts (hunk 2 above)
Comment (ramanxg) [reply helpers/week.helper.ts:244]: I think you mean for line 7. If I add the types, I'll get an error looking like this, since query parameters in the url can be multiple types. I considered making this a separate issue, but if we can fix it now that also works. 

image

File: graphql/schema.ts (hunk 7 above)
Comment (Edwu29) [reply graphql/schema.ts:166]: That sounds like an appropriate name

File: helpers/week.helper.ts (hunk 2 above)
Comment (Edwu29) [reply helpers/week.helper.ts:244]: I found a solution for this. It involves creating a new type and setting the url query to be that type and then passing it into the function getWeek. getWeek can now have type string. If there is a cleaner solution that would be better.
Screen Shot 2022-05-02 at 8 33 55 PM 
Screen Shot 2022-05-02 at 8 35 58 PM

Comment (Edwu29) [reply helpers/week.helper.ts:244]: Referenced from: https://errorsfixing.com/express-argument-of-type-parsedqs-is-not-assignable-to-parameter-of-type-xxxx/

**Review by Edwu29 — COMMENTED** [review]
GraphQL files look good!

File: helpers/grades.helper.ts [hunk 8]
```diff
@@ -1,15 +1,14 @@
...
+import db, { Database } from "better-sqlite3";
+import path from 'path';
+import { ValidationError } from "./errors.helper";
+import { GradeDist, GradeCalculatedData, GradeRawData, WhereParams} from "../types/types"
 
 // Constructs a WHERE clause from the query
-function parseGradesParamsToSQL(query) {
-    var whereClause = "";
-    var paramsList = [];
+export function parseGradesParamsToSQL(query) : WhereParams{
```
Comment (Edwu29) [inline helpers/grades.helper.ts:7]: can add typecheck to query, {[key: string]: any}

File: helpers/grades.helper.ts [hunk 9]
```diff
@@ -107,30 +106,60 @@ function parseGradesParamsToSQL(query) {
...
+    NULLIF(averageGPA, '') as averageGPA FROM gradeDistribution`;
+    return queryDatabase(sqlStatement + where.where).bind(where.params).all();
+    
 }
 
-function fetchInstructors(where) {
+
+export function fetchInstructors(where: WhereParams) : string[] {
     let sqlStatement = "SELECT DISTINCT instructor FROM gradeDistribution";
-    return queryDatabase(where.where !== null ? sqlStatement + where.where : sqlStatement).bind(where.params).all().map(result => result.instructor);
```
Comment (Edwu29) [inline helpers/grades.helper.ts:129]: i think its better to have the check if where clause is null? not sure

**Review by Edwu29 — COMMENTED** [review]
Other than that, looks good. The function queryDatabaseAndResponse looks much better.

File: helpers/grades.helper.ts (hunk 8 above)
Comment (ramanxg) [reply helpers/grades.helper.ts:7]: Good catch.

File: helpers/grades.helper.ts (hunk 9 above)
Comment (ramanxg) [reply helpers/grades.helper.ts:129]: I had it removed, since I didn't think it would ever occur. If you think it's better, I'll add it back.

Comment (Edwu29) [reply helpers/grades.helper.ts:129]: I think its better in my opinion because there might be a query with no where clause?

**Comment by Edwu29** [comment]
I haven't looked at all the files in detail. Is there a way to get the rewrite in production and revert to the old master if needed? Or if you're confident in it, I'm all for it. I don't think typescript should have much impact on the functionality of the API.

**Comment by ramanxg** [comment]
> I haven't looked at all the files in detail. Is there a way to get the rewrite in production and revert to the old master if needed? Or if you're confident in it, I'm all for it. I don't think typescript should have much impact on the functionality of the API.

We can always revert to old version through GitHub. Since most of the code logic/functionality wasn't changed I'm pretty confident.

**Review by Edwu29 — APPROVED** [review]
